server.port=80

spring.application.name=TestEcsAws

# Configuration H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ============================================
# Configuration AWS S3
# ============================================

# Région AWS
aws.region=us-east-1

# Informations du bucket S3
aws.s3.bucket-name=test-roudane-bucket
aws.s3.region=us-east-1

# Configuration pour MultipartFile upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
